#Copy File and RUN
#.---

- name: Install epel
  yum: name=epel-release state=latest

- name: Install nginx
  yum: name=nginx state=latest

- name: Create a User {{allusers.gitlab.name}}
  user: name={{allusers.gitlab.name}} uid={{allusers.gitlab.id}} groups=docker password=Start12345


- name: Firewall
  firewalld: service={{item}} permanent=true state=enabled zone=public
  with_items:
        - http
        - https
  notify:
        - reload firewalld
 
- name: Create Folder for owncloud Files
  file: state=directory path={{item}} mode=0777
  with_items:
      - /etc/nginx/conf.d    
      - /etc/nginx/ssl
      - /home/{{allusers.gitlab.name}}/gitlab/
      - /home/{{allusers.gitlab.name}}/gitlab/logs  
      - /home/{{allusers.gitlab.name}}/gitlab/data
      


        #- name: create self-signed SSL cert
        #command: openssl req -x509 -nodes -days 365 -newkey rsa:4096 -subj "/C=US/ST=la/L=po/O=IT/CN=jonnybravoserver-gitlab" -keyout /etc/nginx/ssl/nginx_gitlab.key -out /etc/nginx/ssl/nginx_gitlab.crt
   # notify: reload ngin
 
- name: Create a service
  template: src={{item.src}} dest={{item.dest}}
  with_items:
          #  - {src: nginx_gitlab.conf, dest: /etc/nginx/conf.d/nginx_gitlab.conf}
        - {src: gitlab.service.j2, dest: /etc/sysconfig/gitlab}


- name: Register Unit Dokuwiki
  template: src=gitlab.service.j2 dest=/lib/systemd/system/gitlab.service mode=644
  notify:
       - reload systemctl
         #- reload nginx

- name: Start Service gitlab
  service: name={{item}} state=restarted enabled=yes
  with_items:
     - gitlab.service    
       #    - nginx


