<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jonnybravo
 * Date: Mon, 18 May 2015 23:03:02 +0200
 */

$conf['title'] = 'JonnysWiki';
$conf['lang'] = 'de';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['plugin']['siteexport']['skipacl'] = 1;
$conf['plugin']['siteexport']['useOddEven'] = 1;

// end auto-generated content
