---
    - name: install the latest version of yum
      dnf:
      name: yum
      state: latest
    - name: Install python setup tools
      yum: name=python-setuptools
    - name: Install Pypi
      easy_install: name=pip
    - name: Install docker-py
      pip: name={{ item }}
      with_items:
        docker-py
        docker-compose
    - name: Install Docker
      yum: name=docker state=latest
      when: ansible_distribution == "CentOS" or ansible_distribution == "Fedora"
    - name: create a docker Group
      group: name=docker state=present
    - name: Adding existing user {{ lookup('env','USER') }} to group sudo
      user: name=jonnybravo groups=docker append=yes
    - name: Make sure Docker is running
      service: name=docker state=running enabled=yes
