---
 - name: install very imported Apps for Ubuntu
   apt: name={{ item }}
   with_items:
     - python-pip
     - python
   when:
    - ansible_distribution == "Ubuntu"
 - name: install very imported Apps for CentOS
   yum: name={{ item }} update_cache=yes
   with_items:
    - epel-release
   when:
    - ansible_distribution == "CentOS"
 - name: Update system
   yum: name=* update_cache=yes state=latest
   when:
    - ansible_distribution == "CentOS"
 - name: install very imported Apps for CentOS part two
   yum: name={{ item }} update_cache=yes
   with_items:
     - python-pip
     - python
     - python-twisted-core
   when:
     - ansible_distribution == "CentOS"
       # - name: Copy Files Honeypy
       #copy: src=py dest={{ ziel }} mode=0777
 
 - name: Copy Script 
   copy: src=check_honey_and_run_it.sh dest={{ ziel }}
 
 - name: upgrade pip
   command: 'pip install --upgrade pip'
 
 - name: install requerments
   pip: name={{ item.name }} version={{ item.version }}
   with_items:
     - { name: 'dnslib', version: '0.9.7' }
     - { name: 'pika', version: '0.10.0' }
     - { name: 'requests', version: '2.6.0' }
 - name: install req two
   pip: name={{ item }}
   with_items:
     - urllib3
     - certifi
 - name: start HoneyPot
   raw: nohup python {{ ziel }}py/Honey.py -d </dev/null >/dev/null 2>&1 & sleep 1 
